language: r
warnings_are_errors: false
cache:
  packages: true
script:
- Rscript -e "rmarkdown::render_site()"
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after _site pfs400wm@karli.rrze.uni-erlangen.de:/proj/websource/docs/FAU/fakultaet/phil/www.datascience.phil.fau.de/websource
  on:
    branch: master
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_4f4c68a93cef_key -iv $encrypted_4f4c68a93cef_iv
  -in id_rsa.pub.enc -out ~\/.ssh/id_rsa.pub -d
