language: r
warnings_are_errors: false
cache:
  packages: true
addons:
  ssh_known_hosts: karli.rrze.uni-erlangen.de
install:
  - echo AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFHJVSekYKuF5pMKyHe1jS9mUkXMWoqNQe0TTs2sY1OQj379e6eqVSqGZe+9dKWzL5MRFpIiySRKgvxuHhaPQU4= >> $HOME/.ssh/known_hosts
# this is to establish karli as known host, but protecting against man-in-the-middle, as per https://docs.travis-ci.com/user/ssh-known-hosts/
script:
- Rscript -e "rmarkdown::render_site()"
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after _site pfs400wm@karli.rrze.uni-erlangen.de:/proj/websource/docs/FAU/fakultaet/phil/www.datascience.phil.fau.de/websource
  on:
    branch: master
notifications:
  email: false
before_deploy:
- openssl aes-256-cbc -K $encrypted_4f4c68a93cef_key -iv $encrypted_4f4c68a93cef_iv
  -in deploy_rsa.enc -out deploy_rsa -d
