language: r
warnings_are_errors: false
cache:
  packages: true
script:
- Rscript -e "rmarkdown::render_site()"
deploy:
  provider: pages
  skip_cleanup: true
  local-dir: _site/
  github-token: "$GITHUB_TOKEN"
  on:
    branch: master
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_4f4c68a93cef_key -iv $encrypted_4f4c68a93cef_iv
  -in id_rsa.pub.enc -out ~\/.ssh/id_rsa.pub -d
